[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"
